[tools]
uv = "latest"
ruff = "latest"
ty = "latest"
stylua = "latest"

[settings]
python.uv_venv_auto = "source"
python.compile = false

[settings.pipx]
uvx = true

[tasks."build:py"]
description = "build VNDB quotes with Python"
run = "uv run format.py"

[tasks."build:lua"]
description = "build VNDB quotes with Lua"
run = "lua format.lua"

[tasks."lint:py"]
description = "lint Python code"
run = """
#!/usr/bin/env bash
ruff check --fix *.py
ty check
"""

[tasks."lint:lua"]
description = "lint Lua code"
run = """
#!/usr/bin/env bash
stylua *.lua
"""

[tasks.lint]
description = "run linters and apply fixes"
depends = ["lint:*"]

[tasks.clean]
description = "clean outputs"
run = "rm output/vndb* || true"

[tasks.install]
confirm = "fortunes program installed?"
description = "install vndb fortunes"
env.PREFIX = "/usr/share/fortunes"
# env.PREFIX = "/usr/share/games/fortunes"
run = "sudo install -pm644 ${MISE_PROJECT_ROOT}/output/vndb* $PREFIX/"

[tasks.test]
description = "get random VNDB quote"
run = "fortune vndb"

[tasks.uninstall]
description = "remove vndb quotes from fortunes"
env.PREFIX = "/usr/share/fortunes"
# env.PREFIX = "/usr/share/games/fortunes"
run = "sudo rm $PREFIX/vndb{,.dat}"
