name: release

on:
  schedule:
    - cron: 0 4 * * 0 # 4:00 UTC every Sunday
  workflow_dispatch:

permissions: {}

jobs:
  build:
    permissions:
      contents: write # required to make release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]
    steps:
      - name: checkout repo
        uses: actions/checkout@v5
        with:
          persist-credentials: false

      - name: setup project with mise
        id: setup-mise
        uses: jdx/mise-action@v3
        with:
          install: true
          cache: true
          tool_versions: |
            python ${{ matrix.python-version }}

      - name: build vndb quotes
        run: |
          sudo apt install -y fortune-mod
          mise run build:py

      - name: upload artifact to release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          prerelease: false
          tag: continuous
          omitBody: true
          omitBodyDuringUpdate: true
          omitNameDuringUpdate: true
          artifacts: output/vndb*
          token: ${{ secrets.GITHUB_TOKEN }}
