name: release

on:
  schedule:
    - cron: "0 4 * * 0" # 4:00 UTC every Sunday
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: make fortune dat
        run: |
          sudo apt install -y fortune-mod lua5.4
          make run

      - name: upload artifact to release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: True
          prerelease: False
          tag: "continuous"
          omitBody: True
          omitBodyDuringUpdate: True
          omitNameDuringUpdate: True
          artifacts: "output/vndb*"
          token: ${{ secrets.GITHUB_TOKEN }}
