name: release

on:
  schedule:
    - cron: 0 4 * * 0 # 4:00 UTC every Sunday
  workflow_dispatch:

permissions: {}

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: make fortune dat
        run: |
          sudo apt install -y fortune-mod
          python format.py

      - name: upload artifact to release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          prerelease: false
          tag: continuous
          omitBody: true
          omitBodyDuringUpdate: true
          omitNameDuringUpdate: true
          artifacts: output/vndb*
          token: ${{ secrets.GITHUB_TOKEN }}
